# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[(b'CQ', b'Cheque'), (b'CS', b'Cash')], max_length=2)),
                ('receipt_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[(b'm', b'Male'), (b'f', b'Female')], max_length=1)),
                ('email_address', models.CharField(max_length=128)),
                ('email_address2', models.CharField(blank=True, max_length=128)),
                ('phone_number', models.CharField(max_length=13)),
                ('phone_number2', models.CharField(blank=True, max_length=13)),
                ('physical_address', models.TextField(null=True)),
                ('post_code', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[(b'm', b'Male'), (b'f', b'Female')], max_length=1)),
                ('status', models.CharField(choices=[(b'a', b'Active'), (b'p', b'Prospective'), (b'x', b'Inactive')], max_length=1)),
                ('email_address', models.CharField(max_length=128)),
                ('email_address2', models.CharField(blank=True, max_length=128)),
                ('phone_number', models.CharField(max_length=13)),
                ('phone_number2', models.CharField(blank=True, max_length=13)),
                ('physical_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-last_name']},
        ),
        migrations.AddField(
            model_name='student',
            name='medical_information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_permitted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[(b'a', b'Active'), (b'p', b'Prospective'), (b'x', b'Inactive')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[(b'm', b'Male'), (b'f', b'Female')], max_length=1),
        ),
        migrations.AddField(
            model_name='termdate',
            name='attendances',
            field=models.ManyToManyField(to='sms.Student'),
        ),
        migrations.AddField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Student'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='students',
            field=models.ManyToManyField(to='sms.Student'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Subject'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.Parent'),
        ),
    ]
